import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { generate } from './generator.ts';
const ORIGIN='https://yuubae96-rgb.github.io';
const BASE=Deno.env.get('SUPABASE_URL')!;
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const reply=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Origin':ORIGIN,'Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store','Vary':'Origin'}});
async function db(path:string,body?:unknown,method?:string){const r=await fetch(BASE+'/rest/v1/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',Prefer:'return=representation'},...(body===undefined?{}:{body:JSON.stringify(body)})});const txt=await r.text();if(!r.ok){console.error('video job database error',r.status);throw Error('生成状態を保存できませんでした。もう一度確認してください。')}return txt?JSON.parse(txt):null;}
const rpc=(name:string,body={})=>db('rpc/'+name,body);
async function hash(token:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function workerToken(){return String(await rpc('video_jobs_worker_token'));}
async function kick(){const token=await workerToken();await fetch(BASE+'/functions/v1/video-background-jobs',{method:'POST',headers:{'Content-Type':'application/json','x-video-worker-token':token},body:'{"action":"work"}',signal:AbortSignal.timeout(10000)}).then(r=>r.body?.cancel()).catch(e=>console.error('worker kickoff failed',e.name));}
function background(p:Promise<unknown>){EdgeRuntime.waitUntil(p.catch(e=>console.error('video background task',String(e.message).slice(0,200))));}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function voicevox(b:any){const r=await fetch('https://api.tts.quest/v3/voicevox/synthesis',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({text:b.text,speaker:String(b.speaker||13)}),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!d.success)throw Error(d.message||'VOICEVOXの生成開始に失敗しました');const deadline=Date.now()+90000;while(Date.now()<deadline){const s=await fetch(d.audioStatusUrl,{signal:AbortSignal.timeout(10000)}).then(r=>r.json());if(s.isAudioError)throw Error('VOICEVOXの音声生成に失敗しました');if(s.isAudioReady){const r=await fetch(d.mp3DownloadUrl||d.wavDownloadUrl,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('完成音声を保存できませんでした');const a=new Uint8Array(await r.arrayBuffer());let text='';for(let i=0;i<a.length;i+=32768)text+=String.fromCharCode(...a.subarray(i,i+32768));return {data:btoa(text),mimeType:r.headers.get('content-type')||'audio/mpeg',provider:'voicevox',alignment:[]};}await sleep(1500);}throw Error('VOICEVOXの生成が時間内に完了しませんでした。再試行してください');}
async function work(){const item=await rpc('video_jobs_claim');if(!item)return;let result=null,error=null;try{if(item.request.action==='generateVoicevoxTts')result=await voicevox(item.request);else{const response=await generate(new Request(BASE+'/functions/v1/video-ai-gemini',{method:'POST',headers:{Origin:ORIGIN,'Content-Type':'application/json'},body:JSON.stringify(item.request)}));result=await response.json();if(!response.ok)throw Error(result.error||'生成に失敗しました');}if(!result?.data)throw Error('生成結果が空でした');if(JSON.stringify(result).length>15000000)throw Error('生成結果が大きすぎます');}catch(e){result=null;error=String((e as Error).message||e).slice(0,800);}await rpc('video_jobs_finish',{p_id:item.id,p_lease:item.lease,p_result:result,p_error:error});await kick();}
function validate(items:any[]){if(!Array.isArray(items)||!items.length||items.length>120)throw Error('生成の件数を確認してください');return items.map((x:any)=>{if(!Number.isInteger(x.sceneIndex)||x.sceneIndex<0||x.sceneIndex>59||!['image','audio'].includes(x.kind))throw Error('場面の指定が不正です');const b=x.request||{};if(x.kind==='image'){if(b.action!=='generateImage'||!String(b.prompt||'').trim()||String(b.prompt).length>50000)throw Error('画像指示を確認してください');if(!['gemini','openai','auto'].includes(b.imageProvider||'auto'))throw Error('画像AIの指定を確認してください');}else if(!['generateFishTts','generateTts','generateVoicevoxTts'].includes(b.action)||!String(b.text||'').trim()||String(b.text).length>12000)throw Error('音声の文章を確認してください');return {sceneIndex:x.sceneIndex,kind:x.kind,request:b};});}
Deno.serve(async req=>{if(req.method==='OPTIONS')return reply({});try{if(req.method!=='POST')return reply({error:'Method not allowed'},405);const b=await req.json();if(b.action==='work'){const supplied=req.headers.get('x-video-worker-token');if(!supplied||supplied!==await workerToken())return reply({error:'Forbidden'},403);background(work());return reply({accepted:true});}if(req.headers.get('origin')!==ORIGIN)return reply({error:'Forbidden origin'},403);if(!/^[a-f0-9]{64}$/.test(b.token||'')||!/^[-a-f0-9]{36}$/.test(b.jobId||''))return reply({error:'Invalid session'},401);const owner=await hash(b.token);if(b.action==='create'){const items=validate(b.items);if(JSON.stringify(b.snapshot||{}).length>250000)throw Error('構成が大きすぎます');await rpc('video_jobs_enqueue',{p_id:b.jobId,p_owner:owner,p_snapshot:b.snapshot||{},p_items:items});background(kick());return reply({jobId:b.jobId,accepted:true});}
const jobs=await db('video_background_jobs?id=eq.'+encodeURIComponent(b.jobId)+'&owner_hash=eq.'+owner+'&select=id,snapshot,cancelled,created_at');if(!jobs?.length)return reply({error:'この生成結果は見つかりません。保存期間は30日です。'},404);
if(b.action==='status'){const items=await db('video_background_items?job_id=eq.'+b.jobId+'&select=id,scene_index,kind,status,error,ordinal&order=ordinal.asc');return reply({job:jobs[0],items});}
if(b.action==='result'){if(!/^[-a-f0-9]{36}$/.test(b.itemId||''))return reply({error:'Invalid item'},400);const rows=await db('video_background_items?id=eq.'+b.itemId+'&job_id=eq.'+b.jobId+'&status=eq.done&select=result');return rows.length?reply(rows[0].result):reply({error:'まだ完成していません'},409);}
if(b.action==='cancel'){await db('video_background_jobs?id=eq.'+b.jobId,{cancelled:true},'PATCH');await db('video_background_items?job_id=eq.'+b.jobId+'&status=eq.queued',{status:'cancelled'},'PATCH');return reply({cancelled:true});}
return reply({error:'Unknown action'},400);}catch(e){return reply({error:String((e as Error).message||e)},400);}});
